<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="avatar.webp" />
    <None Remove="Sport Wallpaper.jpg" />
    <None Remove="Summa_Move2_transparant.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="avatar.webp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="Sport Wallpaper.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Summa_Move2_transparant.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
